document.write('        <footer id="ABdev_main_footer">	');
document.write('            <div id="footer_columns">	');
document.write('                <div class="container">	');
document.write('                    <div class="row">	');
document.write('                        <div class="span4 clearfix">	');
document.write('                            <div id="text-6" class="widget widget_text">	');
document.write('                                <h3 class="footer-widget-heading">DAILY ENCOURAGEMENT</h3>	');
document.write('                                <div class="textwidget">	');
document.write('                                    <a target="_blank" href="https://biblia.com/bible/kjv/verseoftheday">	');
document.write('                                        <img src="https://biblia.com/api/plugins/verseoftheday/kjv?width=300&height=250&singleImage=true&theme=imagebased&variant=light" width="300" height="250" />	');
document.write('                                    </a>	');
document.write('                                </div>	');
document.write('                            </div>	');
document.write('                        </div>	');
document.write('                        <div class="span4 clearfix">	');
document.write('                            <div id="recent-posts-3" class="widget widget_recent_entries">	');
document.write('                                <h3 class="footer-widget-heading">WHEN WE MEET</h3>	');
document.write('                                <div class="contact_info_widget">	');
document.write('                                    <strong><u>SUNDAY MORNING</u></strong><br>	');
document.write('                                    &nbsp;&nbsp;&nbsp;9:30 am Worship<br>&nbsp;11:00 am Classes for all ages<br><br>	');
document.write('                                    <strong><u>SUNDAY EVENING</u></strong><br>	');
document.write('                                    &nbsp;&nbsp;&nbsp;Small Group Meetings<br>&nbsp;&nbsp;&nbsp;Contact church office<br><br>	');
document.write('                                </div>	');
document.write('                            </div>	');
document.write('                        </div>	');
document.write('                        <div class="span4 clearfix">	');
document.write('                            <div id="contact-info-2" class="widget contact-info">	');
document.write('                                <h3 class="footer-widget-heading">WHERE WE MEET</u></h3>	');
document.write('                            <div class="contact_info_widget">	');
document.write('                                <p><i class="ci_icon-home2"></i>Webb Chapel church of Christ<br>13425 Webb Chapel Road,<br>Farmers Branch, Texas 75234</p>	');
document.write('                                <p class="no_margin_bottom"><i class="ci_icon-call2"></i>(972) 241-3293</p>	');
document.write('                                <p><i class="ci_icon-mail-empty"></i> <a style="text-decoration:underline;" href="' + varcocrootpath + 'contact.html">Email Us</a></p>	');
document.write('                                <p>Charity ID: 75-1155632   ');
document.write('                            </div>	');
document.write('                        </div>	');
document.write('                    </div>	');
document.write('                </div>	');
document.write('            </div>	');
document.write('        </div>	');
document.write('    </footer>	');
document.write('    <div id="footer_copyright">	');
document.write('        <div class="container">	');
document.write('            <div class="row">	');
document.write('                <div id="footer_container">	');
document.write('                    <div class="row">	');
document.write('                        <div class="copyright span6">	');
document.write('                            &copy; Overseen by the Webb Chapel church of Christ Eldership	');
document.write('                        </div>	');
document.write('                        <div id="footer_social" class="span6">	');
document.write('                            <a href="https://www.facebook.com/WebbChapelUpdates" target="_blank"><i class="ci_icon-facebook"></i></a>	');
document.write('                            <a href="https://twitter.com/webbchapel" target="_blank"><i class="ci_icon-twitter"></i></a>	');
document.write('                            <a href="https://www.youtube.com/@WCCConline" target="_blank"><i class="ci_icon-youtube"></i></a>	');
document.write('                        </div>	');
document.write('                    </div>	');
document.write('                </div>	');
document.write('            </div>	');
document.write('            <div class="back_to_top">	');
document.write('                <a href="" id="back_to_top" title="Scroll to top"></a>	');
document.write('            </div>	');
document.write('        </div>	');
document.write('    </div>	');
